export enum EventStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  QUORUM_REACHED = 'QUORUM_REACHED',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  SOLD_OUT = 'SOLD_OUT',
  COMPLETED = 'COMPLETED',
}
